name: Python Application Test with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: make install

      - name: Format code
        run: make format

      - name: Lint code
        run: make lint

      - name: Container lint
        run: make container-lint
